In [1]:
import pickle, tfidf
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop
from keras.models import model_from_json

Using TensorFlow backend.
C:\Users\1\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\1\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\1\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1

In [2]:
text1 ="""
대통령이 북한과 관련된 이야기로 한미 정상회담을 준비하고 있습니다.
"""
text2="""
iPhone과 iPad를 모두 가지고 다니므로 USB를 2개 연결할 수 있는 휴대용 배터리를 선호합니다.
"""

text3="""
이번 주에는 미세먼지가 많을 것으로 예상되므로 노약자는 외출을 자제하는 것이 좋습니다.
"""

In [3]:
tfidf.load_dic("genre-tfidf.dic")

In [4]:
nb_classes = 4
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(37414,)))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(nb_classes, activation='softmax'))
model.compile(
    loss='categorical_crossentropy',
    optimizer=RMSprop(),
    metrics=['accuracy'])
model.load_weights('./genre-model.hdf5')

In [7]:
def check_genre(text) :
    LABELS = ["정치","경제","생활","IT/과학"]
    data = tfidf.calc_text(text)
    pre = model.predict(np.array([data]))[0]
    n = pre.argmax()
    print(pre)
    print(n)
    print(LABELS[n], "(",pre[n], ")")
    return LABELS[n], float(pre[n]), int(n)

In [8]:
if __name__ == '__main__':
    check_genre(text1)
    check_genre(text2)
    check_genre(text3)

[1.0000000e+00 1.5872098e-10 1.9583563e-08 7.9206539e-14]
0
정치 ( 1.0 )
[2.92795765e-09 2.14033978e-04 1.06876236e-07 9.99785841e-01]
3
IT/과학 ( 0.99978584 )
[1.3660156e-09 2.2318858e-07 9.9999976e-01 5.0747706e-10]
2
생활 ( 0.99999976 )
